// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModernRecrut.Postulation.API.Data;

#nullable disable

namespace ModernRecrut.Postulation.API.Migrations
{
    [DbContext(typeof(PostulationsContext))]
    partial class PostulationsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ModernRecrut.Postulation.API.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NomEmeteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoteDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostulationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PostulationId");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("ModernRecrut.Postulation.API.Models.Postulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CandidatId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateDisponibilite")
                        .HasColumnType("datetime2");

                    b.Property<int>("OffreDEmploiId")
                        .HasColumnType("int");

                    b.Property<decimal>("PretentionSalariale")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Postulation");
                });

            modelBuilder.Entity("ModernRecrut.Postulation.API.Models.Note", b =>
                {
                    b.HasOne("ModernRecrut.Postulation.API.Models.Postulation", "Postulation")
                        .WithMany("Notes")
                        .HasForeignKey("PostulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Postulation");
                });

            modelBuilder.Entity("ModernRecrut.Postulation.API.Models.Postulation", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
